name: learn-github-actions
on: [push, pull_request]
jobs:
  check-bats-version:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v